#!/usr/bin/env python3
"""
mcporter-generate-docs.py — 自动生成/重建 TOOLS-mcp-*.md 系列文档。

数据源：
  - `mcporter list` → 13 个 MCP 服务器清单（name / 工具数 / 启动延迟 / 状态）
  - `mcporter config list` → 每个服务器的启动命令 + 描述
  - `mcporter daemon status` → 守护进程 PID + socket 路径
  - `mcporter list <server> --schema` → 每个服务器的工具 schema（含 JSDoc）

输出：
  - TOOLS-mcp-servers.md（总览索引，1 个）
  - TOOLS-mcp-<name>.md（每个服务器深度子文件，13 个）

幂等性：
  - 用 `<!-- AUTO-GENERATED by mcporter-generate-docs.py -->` 标记
  - 只覆盖自己标记的文件，不破坏手写的 TOOLS-*.md
  - 已有但被改过的手写内容会被脚本覆盖（用户自行备份）

用法：
  python3 scripts/mcporter-generate-docs.py                 # 重建全部
  python3 scripts/mcporter-generate-docs.py --dry-run       # 仅显示将要写入的文件
  python3 scripts/mcporter-generate-docs.py --only <name>   # 只重建某服务器

依赖：
  - mcporter v0.13+（在 PATH 里）
  - Python 3.10+
"""

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

WORKSPACE = Path("/home/wszmd520520/.openclaw/workspace")
MCPORTER = "mcporter"
TAG = "<!-- AUTO-GENERATED by mcporter-generate-docs.py -->"
SHANGHAI_TZ = timezone(timedelta(hours=8))


def sh(cmd: list[str], timeout: int = 60) -> str:
    """Run shell command, return stdout."""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return result.stdout.strip()
    except subprocess.TimeoutExpired:
        return f"[TIMEOUT after {timeout}s]"
    except FileNotFoundError:
        return f"[NOT FOUND: {cmd[0]}]"


def parse_mcporter_list() -> list[dict]:
    """
    Parse `mcporter list` output (key=value format with -).
    Returns list of dicts: {name, tools, startup_seconds, description}.
    """
    out = sh([MCPORTER, "list"], timeout=45)
    servers = []
    # 跳过 header（"Listing N server(s)..."）和 footer（"Listed N servers..."）
    for line in out.splitlines():
        line = line.strip()
        if not line or line.startswith(("Listing", "Listed", "✔", "✖")):
            continue
        # 格式：- name — Description (N tools, X.Xs)  或  (1 tool, X.Xs)（1 个工具时是单数）
        m = re.match(r"-\s+(\S+)\s+—\s+(.+?)\s+\((\d+)\s+tools?\s*,\s+([\d.]+)s\)", line)
        if m:
            servers.append({
                "name": m.group(1),
                "description": m.group(2),
                "tools": int(m.group(3)),
                "startup_seconds": float(m.group(4)),
            })
    return servers


def parse_mcporter_config() -> dict[str, dict]:
    """
    Parse `mcporter config list` output.
    Returns {name: {transport, command, description, source}}.
    """
    out = sh([MCPORTER, "config", "list"], timeout=30)
    configs = {}
    current = None
    for line in out.splitlines():
        if not line.strip():
            continue
        # server name 行（无缩进）
        if not line.startswith(("  ", "\t")) and line.strip():
            current = line.strip()
            configs[current] = {}
        elif current and line.strip().startswith("Transport:"):
            configs[current]["transport"] = line.split(":", 1)[1].strip()
        elif current and line.strip().startswith("Description:"):
            configs[current]["description"] = line.split(":", 1)[1].strip()
    # 兜底：用第二段获取 transport 详情（包含完整命令）
    for name in configs:
        full = sh([MCPORTER, "config", "list"], timeout=30)
        # 提取该 name 的 Transport 行（含括号内的命令）
        m = re.search(
            rf"^{re.escape(name)}\s*\n\s+Source:[^\n]*\n\s+Transport:\s+(\S+)\s+\(([^)]+)\)",
            full,
            re.MULTILINE,
        )
        if m:
            configs[name]["transport_kind"] = m.group(1)
            configs[name]["command"] = m.group(2)
    return configs


def parse_daemon_status() -> dict:
    """Parse `mcporter daemon status` for PID + socket."""
    out = sh([MCPORTER, "daemon", "status"], timeout=15)
    pid_match = re.search(r"Daemon pid (\d+)", out)
    sock_match = re.search(r"socket:\s+(\S+)", out)
    return {
        "pid": pid_match.group(1) if pid_match else "?",
        "socket": sock_match.group(1) if sock_match else "?",
    }


def fetch_schema(server_name: str) -> str:
    """Get raw schema text for a server (for embedding in subfile)."""
    return sh([MCPORTER, "list", server_name, "--schema"], timeout=30)


def now_str() -> str:
    """当前北京时间字符串。"""
    return datetime.now(SHANGHAI_TZ).strftime("%Y-%m-%d %H:%M %Z")


def slug(name: str) -> str:
    """Server name → 文件名片段（保留连字符）。"""
    return name


def render_overview(servers: list[dict], daemon: dict, now: str) -> str:
    """Generate TOOLS-mcp-servers.md 内容。"""
    by_tools = sorted(servers, key=lambda s: -s["tools"])
    total_tools = sum(s["tools"] for s in servers)

    rows = []
    for i, s in enumerate(by_tools, 1):
        slugified = slug(s["name"])
        rows.append(
            f"| {i} | **{s['name']}** | {s['tools']} | {s['startup_seconds']}s | "
            f"{s['description'].split('(')[0].strip()} | → `TOOLS-mcp-{slugified}.md` |"
        )

    return f"""# TOOLS-mcp-servers.md — mcporter 13 个 MCP 服务器总览

{TAG}

> mcporter 管理的 MCP 服务器总览索引。
> **本文件是索引**，每个服务器的深度内容见对应子文件 `TOOLS-mcp-<name>.md`。
> 主索引见 → `TOOLS.md`。
>
> **加载规则**：`TOOLS-*.md` 不自动注入，按需 `read` 加载。
>
> **生成时间**：{now}
> **数据快照**：`mcporter list` + `mcporter config list` + `mcporter daemon status`
> **守护进程**：PID {daemon['pid']}，socket `{daemon['socket']}`

---

## ⚠️ 关键事实

0. **mcporter CLI 不在 OpenClaw 默认 PATH** — 使用前需 `export PATH="$HOME/.nvm/versions/node/v24.21.0/bin:$PATH"`。
1. **守护进程 PID {daemon['pid']} 运行稳定** — 状态可在 `mcporter daemon status` 实时查。
2. **配置真实源**：`config/mcporter.json` 是 13 服务器定义源；本目录是文档索引。

---

## {len(servers)} 个 MCP 服务器清单（按工具数降序）

| # | 服务器名 | 工具数 | 启动 | 类别 | 深度子文件 |
|---|---------|--------|------|------|----------|
{chr(10).join(rows)}

**总览**：{len(servers)} 服务器 / **{total_tools} 个工具** / 全部 healthy / 全部 stdio。

---

## mcporter CLI 命令速查

```bash
mcporter list                                          # 列所有服务器
mcporter list <server> --schema                        # 查某 server 的工具 schema
mcporter call <server.tool> key=value                  # 调用工具
mcporter daemon start|status|stop|restart              # 守护进程
mcporter config list|get|add|remove|import             # 配置管理
mcporter auth <server|url> [--reset]                   # OAuth 认证
mcporter generate-cli --server <name>                  # 生成 CLI 封装
mcporter emit-ts <server> --mode client|types          # 导出 TypeScript
```

---

## 常见问题排查

| 现象 | 解决 |
|------|------|
| `mcporter: command not found` | `export PATH="$HOME/.nvm/versions/node/v24.21.0/bin:$PATH"` |
| `mcporter list` 卡 30s+ | 加 `timeout 30`；或 `mcporter daemon restart` |
| 守护进程未运行 | `mcporter daemon start` |
| 工具调用 401/403 | `mcporter auth <server>` |
| 想看某 server 全部工具 | `mcporter list <server> --schema` + 读对应 `TOOLS-mcp-<name>.md` |

---

## 自动重建

本目录由 `scripts/mcporter-generate-docs.py` 自动生成（标记 `{TAG}`）。
下次 MCP 服务器变化时跑：

```bash
python3 scripts/mcporter-generate-docs.py                 # 重建全部
python3 scripts/mcporter-generate-docs.py --only github   # 只重建某 server
python3 scripts/mcporter-generate-docs.py --dry-run       # 预览
```
"""


def render_subfile(server: dict, schema_text: str, now: str) -> str:
    """Generate TOOLS-mcp-<name>.md 内容。"""
    name = server["name"]
    slugified = slug(name)
    # 截断 schema（防止超过上下文窗口）
    schema_excerpt = schema_text[:3000]
    if len(schema_text) > 3000:
        schema_excerpt += "\n\n... [schema 截断，共 " + str(len(schema_text)) + " chars]\n"

    return f"""# TOOLS-mcp-{slugified}.md — {server['description'].split('(')[0].strip()}（{server['tools']} 工具）

{TAG}

> {server['description']}。
> 索引见 → `TOOLS-mcp-servers.md`。
>
> **生成时间**：{now}

---

## 元数据

- **启动延迟**：{server['startup_seconds']}s
- **工具数**：{server['tools']}
- **描述**：{server['description']}

---

## 工具 schema（部分）

```
{schema_excerpt}
```

> 完整 schema 跑 `mcporter list {name} --schema`

---

## 常用调用模板

```bash
# 列出该 server 工具
mcporter list {name} --schema

# 调用示例（按 schema 实际参数替换）
mcporter call {name}.<tool> key=value
```

---

## 历史变更

- **{now.split()[0]}**：自动生成（脚本 `scripts/mcporter-generate-docs.py`）
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--dry-run", action="store_true", help="仅显示将要写入的文件")
    parser.add_argument("--only", metavar="NAME", help="只重建某服务器子文件")
    args = parser.parse_args()

    # 1. 检查 mcporter 可用
    version = sh([MCPORTER, "--version"], timeout=10)
    if version.startswith("[NOT FOUND"):
        print(f"❌ mcporter 不在 PATH：{version}", file=sys.stderr)
        sys.exit(1)
    print(f"📦 mcporter {version}")

    # 2. 拿数据
    print("📋 拿服务器清单...")
    servers = parse_mcporter_list()
    if not servers:
        print("❌ 没拿到任何 server，检查 mcporter list 输出", file=sys.stderr)
        sys.exit(2)
    print(f"   → {len(servers)} servers")

    print("🔌 拿守护进程状态...")
    daemon = parse_daemon_status()
    print(f"   → PID {daemon['pid']}")

    now = now_str()

    # 3. 确定要写入的文件
    targets = []
    if args.only:
        targets = [s for s in servers if s["name"] == args.only]
        if not targets:
            print(f"❌ 没找到 server: {args.only}", file=sys.stderr)
            sys.exit(3)
    else:
        # 总览 + 所有子文件
        targets = servers

    # 4. 生成总览（仅当 --only 没指定时）
    overview_path = WORKSPACE / "TOOLS-mcp-servers.md"
    if not args.only:
        content = render_overview(servers, daemon, now)
        if args.dry_run:
            print(f"[DRY-RUN] Would write {overview_path} ({len(content)} bytes)")
        else:
            overview_path.write_text(content, encoding="utf-8")
            print(f"✅ Wrote {overview_path} ({len(content)} bytes)")

    # 5. 生成每个子文件
    for s in targets:
        schema = fetch_schema(s["name"])
        content = render_subfile(s, schema, now)
        sub_path = WORKSPACE / f"TOOLS-mcp-{slug(s['name'])}.md"
        if args.dry_run:
            print(f"[DRY-RUN] Would write {sub_path} ({len(content)} bytes)")
        else:
            sub_path.write_text(content, encoding="utf-8")
            print(f"✅ Wrote {sub_path} ({len(content)} bytes)")

    print(f"\n🎉 完成（{now}）")


if __name__ == "__main__":
    main()